baseURL = 'https://lacos21.github.io/'
languageCode = 'pt-br'
DefaultContentLanguage = 'pt'
title = 'Lacos21'
theme = 'ananke'

[pagination]
  pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true  # Permite HTML quando necessário

[imaging]
  quality = 85

[params]
  description = "Laboratório de Conservação no Século 21"
  featured_image = "/images/featured-default.jpg"  # Imagem padrão para todas as páginas
  site_logo = "/images/logo-lacos21.png"  # Sua logo no canto superior esquerdo
  summaryLength = 20
  
  # Paleta de cores em tons de verde (códigos HEX)
  background_color_class = "bg-green-900"
  text_color = "green-50"
  custom_css = ["custom.css"]

[params.social]
  twitter = "https://twitter.com/lacos21"
  facebook = "https://facebook.com/lacos21"
  instagram = "https://instagram.com/lacos21"
  youtube = "https://youtube.com/Lacos21"
  github = "https://github.com/Lacos-21"
[menu]
  [[menu.main]]
    name = "Artigos"
    url = "/artigos"
    weight = 1
  [[menu.main]]
    name = "Equipe"
    url = "/equipe"
    weight = 2
  [[menu.main]]
    name = "Projetos"
    url = "/projetos"
    weight = 3
  [[menu.main]]
    name = "MAV"
    url = "/mav"
    weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'